version: '3.7'
services:
  java-srv:
    build:
      context: java-srv
    volumes:
      - ./java-srv/log:/root/log
    depends_on:
      db:
        condition: service_healthy
        restart: true

  db:
    image: mariadb:latest
    ports:
      - 3306
    healthcheck:
      test: "pwd"
    volumes:
      - ./db/sql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=maria
      - MYSQL_PASSWORD=pass
